### ISSUE TITLE
Beacons are non-translucent

### ISSUE THREAD

**Issue by elizabeth-void** [JustinTimeCuber/translucent-glass#3]
![image](https://github.com/JustinTimeCuber/translucent-glass/assets/82621208/6b61b7b6-bab5-4db8-bcd1-152614330c9f)

**Comment by JustinTimeCuber** [comment]
Not sure what the best way to deal with this is. The simple way of fixing this causes some problems when used alongside Sodium due to https://github.com/CaffeineMC/sodium-fabric/issues/38
![2023-12-09_21 28 53](https://github.com/JustinTimeCuber/translucent-glass/assets/46458276/e5911887-5665-4222-863a-5cbf462e2fe0)
I'll consider adding this as an option or detecting the presence of Sodium to determine whether to render beacons as translucent. As a workaround, you could use a resource pack that defines separate textures for glass and beacons rather than sharing the same texture, and then you could have normal-looking beacons alongside translucent glass.
Hopefully, this will be fixed on Sodium's side before too long.

**Comment by JustinTimeCuber** [comment]
Sodium 0.6 is now available, so I am adding translucent beacons in 0.2.1.
